#  dataset
obtain the Hamiltonian of 3-sat instances

In [5]:
import numpy as np

data=np.loadtxt('sat7.txt')
resultc=data.tolist()
print(len(resultc))

218


In [2]:
def satSystem(n_qubit,result):
    N=2**n_qubit


    sx=np.array([[0,1],[1,0]])
    si=np.array([[1,0],[0,1]])

    HB=np.kron(si,si)
    for i in range(n_qubit-2):
        HB=np.kron(si,HB)
    HB=n_qubit*HB/2

    for j in range(n_qubit):
        if j==0:
            B=sx
            for i in range(n_qubit-1-j):
                B=np.kron(si,B) 
        else:    
            for i in range(j):
                if i==0:
                    B=si 
                else: 
                    B=np.kron(si,B)  
            B=np.kron(sx,B)   
            for i in range(n_qubit-1-j):
                B=np.kron(si,B)

        HB=HB-B/2




    HC= np.zeros((N,N))
    for i in result:
        HC[i,i]=HC[i,i]+1
    HP=HC

    return HB,HP

In [3]:
n_qubit=7
result=[int(x) for x in resultc[0]]
HB,HP=satSystem(n_qubit,result)
print(HP)

[[4. 0. 0. ... 0. 0. 0.]
 [0. 2. 0. ... 0. 0. 0.]
 [0. 0. 5. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 2. 0. 0.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 0. ... 0. 0. 3.]]
